(() => {
'use strict';
const mainTime=document.querySelector('#main-time'),mainDate=document.querySelector('#main-date'),world=document.querySelector('#world-grid'),tzLabel=document.querySelector('#tz-label');
const zones=[['Tokyo','Asia/Tokyo'],['UTC','UTC'],['London','Europe/London'],['New York','America/New_York']];
function tickClock(){const now=new Date();mainTime.textContent=new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);mainDate.textContent=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(now);world.innerHTML=zones.map(([name,tz])=>`<div class="world-card"><strong>${new Intl.DateTimeFormat('ja-JP',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:false}).format(now)}</strong><span>${name} · ${new Intl.DateTimeFormat('ja-JP',{timeZone:tz,month:'short',day:'numeric',weekday:'short'}).format(now)}</span></div>`).join('')}
tzLabel.textContent=Intl.DateTimeFormat().resolvedOptions().timeZone||'Local timezone';tickClock();setInterval(tickClock,1000);

const swDisp=document.querySelector('#sw-display'),swStart=document.querySelector('#sw-start'),swLap=document.querySelector('#sw-lap'),swReset=document.querySelector('#sw-reset'),laps=document.querySelector('#laps');let swRunning=false,swBase=0,swStarted=0,swRaf=0,lapN=0;
const fmtSW=ms=>{ms=Math.max(0,ms);const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,cs=Math.floor(ms/10)%100;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(cs).padStart(2,'0')}`};
function swNow(){return swBase+(swRunning?performance.now()-swStarted:0)}function swRender(){swDisp.textContent=fmtSW(swNow());if(swRunning)swRaf=requestAnimationFrame(swRender)}
swStart.addEventListener('click',()=>{if(swRunning){swBase=swNow();swRunning=false;cancelAnimationFrame(swRaf);swStart.textContent='Resume'}else{swStarted=performance.now();swRunning=true;swStart.textContent='Pause';swRender()}});
swLap.addEventListener('click',()=>{const v=swNow();if(v<=0)return;lapN++;const row=document.createElement('div');row.className='history-row';row.innerHTML=`<div class="expr">Lap ${lapN}</div><div class="res">${fmtSW(v)}</div>`;laps.prepend(row)});
swReset.addEventListener('click',()=>{swRunning=false;swBase=0;cancelAnimationFrame(swRaf);lapN=0;laps.innerHTML='';swStart.textContent='Start';swDisp.textContent='00:00.00'});

const tDisp=document.querySelector('#timer-display'),tStart=document.querySelector('#timer-start'),tReset=document.querySelector('#timer-reset');let selected=300,tRemain=selected,tRunning=false,tEnd=0,tInt=0;
const fmtT=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;function tRender(){if(tRunning)tRemain=Math.max(0,Math.ceil((tEnd-Date.now())/1000));tDisp.textContent=fmtT(tRemain);document.title=tRunning?`${fmtT(tRemain)} — Timer`:'Clock — WEB DESK';if(tRunning&&tRemain<=0){tRunning=false;clearInterval(tInt);tStart.textContent='Start';beep();document.title='Clock — WEB DESK'}}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.frequency.value=880;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.18,a.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.55);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.6)}catch{} if('vibrate'in navigator)navigator.vibrate?.([200,100,200])}
tStart.addEventListener('click',()=>{if(tRunning){tRemain=Math.max(0,Math.ceil((tEnd-Date.now())/1000));tRunning=false;clearInterval(tInt);tStart.textContent='Resume'}else if(tRemain>0){tEnd=Date.now()+tRemain*1000;tRunning=true;tStart.textContent='Pause';tInt=setInterval(tRender,250);tRender()}});
tReset.addEventListener('click',()=>{tRunning=false;clearInterval(tInt);tRemain=selected;tStart.textContent='Start';tRender()});document.querySelectorAll('[data-min]').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.min)*60;tRemain=selected;tRunning=false;clearInterval(tInt);tStart.textContent='Start';document.querySelectorAll('[data-min]').forEach(x=>x.classList.toggle('active',x===b));tRender()}));tRender();
})();
